import { test, expect } from '../../fixtures/test-fixtures';
import { unique } from '../../utils/data';

/*
 * Forgot password page — public TCs (Needs = none) generated by prompts/07 from
 * qa/web/01-authentication/authentication-test-cases.md on 2026-09-21.
 *
 * `*.public.spec.ts` → projects chromium-public / firefox-public (no storageState, no
 * setup dependency). Locators come only from screens/authentication/forgot-password.map.ts
 * through the `forgotPasswordPage` fixture (`el.<alias>` = the TC alias). Only expect-*
 * rows assert; each verdict-bearing assertion names its oracle. No sleeps, no skips.
 *
 * TC-AUTH-012 is written to the SRS (FR-AUTH-FP-05/08: no account enumeration) and FAILS on
 * DEV today — observed 2026-09-21: POST /auth/forgot-password answers 404
 * {"message":["User is not found"]} and the page shows an alert "User is not found".
 * That defect is filed as qa/web/01-authentication/bugs/BUG-AUTH-001.md (S3, open, accepted
 * by the client) and is marked `test.fail()` below: a KNOWN ISSUE, not a blocked run.
 * The expectation itself is NOT edited (doctrine rules 1 and 4) — the check keeps proving the
 * defect on every run, the suite stays green, and the day the API answers generically
 * Playwright reports an unexpected pass = the signal to drop the marker and close the bug.
 * trace_results.py still counts the tagged checklist items as Failed (its own rule), so the
 * traceability keeps telling the truth about coverage.
 */

/** {{unknown.email}} — valid format, never registered (TC file → "Fixtures used"). */
const unknownEmail = (): string => `no-such-user+${unique('t')}@example.com`;

test.describe('AUTH — Forgot password page (public)', () => {
  test(
    'TC-AUTH-010 Forgot password page renders the title, description, email field, disabled button and Back to Login',
    { tag: ['@CHK-AUTH-025', '@CHK-AUTH-026', '@CHK-AUTH-027', '@smoke'] },
    async ({ forgotPasswordPage }) => {
      await forgotPasswordPage.open(); // 1 open forgot-password
      await expect(forgotPasswordPage.el.root, 'oracle: SRS §3.1.1.3 — Forgot password page shown').toBeVisible(); // 2
      await expect(forgotPasswordPage.el.logo, 'oracle: SRS §3.1.1.3 logo present').toBeVisible(); // 3
      await expect(forgotPasswordPage.el.title, 'oracle: SRS §3.1.1.3 title (observed 2026-09-17)').toHaveText('Forgot your password?'); // 4
      // 5 — observed copy says "link" (2026-09-17/21); the SRS instruction text says "verification code" — Q-01
      await expect(forgotPasswordPage.el.description, 'oracle: real page 2026-09-21 (SRS wording disputed, Q-01)').toHaveText(
        "Please enter the email address associated with your account, and we'll send you a link to reset your password.",
      );
      // 6 — label without an asterisk on DEV; "marked as required" (CHK-AUTH-026) is Q-20, not proven here
      await expect(forgotPasswordPage.el['email-label'], 'oracle: SRS §3.1.1.3 Email field label (observed 2026-09-17)').toHaveText('Email');
      await expect(forgotPasswordPage.el.email, 'oracle: SRS §3.1.1.3 Email field').toBeVisible(); // 7
      await expect(forgotPasswordPage.el.submit, 'oracle: SRS §3.1.1.3 "Request password reset" button').toBeVisible(); // 8
      await expect(forgotPasswordPage.el.submit, 'oracle: SRS FR-AUTH-FP-03 — disabled until a valid email is entered').toBeDisabled(); // 9
      await expect(forgotPasswordPage.el['back-to-login'], 'oracle: SRS §3.1.1.3 Back to Login available').toBeVisible(); // 10
    },
  );

  test(
    'TC-AUTH-011 Invalid email on Forgot password shows the inline error "Invalid email" and keeps the button disabled',
    { tag: ['@CHK-AUTH-026', '@CHK-AUTH-031', '@core'] },
    async ({ forgotPasswordPage }) => {
      await forgotPasswordPage.open(); // 1
      await forgotPasswordPage.fillEmail('not-an-email'); // 2
      await expect(forgotPasswordPage.el['email-error'], 'oracle: SRS FR-AUTH-FP-02 — inline error for an invalid email').toBeVisible(); // 3
      // 4 — real page wins for what exists today; checklist CHK-AUTH-031 says "Please enter a valid email address" (Q-10)
      await expect(forgotPasswordPage.el['email-error'], 'oracle: copy observed on DEV 2026-09-21 (CHK-031 wording is Q-10)').toHaveText('Invalid email');
      await expect(forgotPasswordPage.el.submit, 'oracle: SRS FR-AUTH-FP-03 — disabled on an invalid email').toBeDisabled(); // 5
      await forgotPasswordPage.fillEmail(''); // 6 — clear the field
      await expect(forgotPasswordPage.el.submit, 'oracle: SRS FR-AUTH-FP-03 — disabled on an empty field').toBeDisabled(); // 7
    },
  );

  test(
    'TC-AUTH-012 Requesting a reset for an unregistered email shows the confirmation state, not an error',
    { tag: ['@CHK-AUTH-030', '@CHK-AUTH-032', '@CHK-AUTH-033', '@core', '@BUG-AUTH-001'] },
    async ({ page, forgotPasswordPage }) => {
      // Known issue BUG-AUTH-001 (account enumeration): expected to fail until the API stops
      // answering 404 "User is not found" for an unknown address. Playwright reports the
      // failure as EXPECTED (suite stays green) and turns the run RED if it ever passes.
      test.fail(true, 'Known issue BUG-AUTH-001 — qa/web/01-authentication/bugs/BUG-AUTH-001.md');
      await forgotPasswordPage.open(); // 1
      await forgotPasswordPage.fillEmail(unknownEmail()); // 2
      await expect(forgotPasswordPage.el.submit, 'oracle: SRS FR-AUTH-FP-03 — enabled for a valid email').toBeEnabled(); // 3
      // 4 — secondary oracle (TC notes, api-contract docs/api/openapi.json#POST /auth/forgot-password):
      // the client sends the request after validation (CHK-AUTH-030/032). Awaited, not a verdict on its own.
      const requestSent = page.waitForResponse(
        (r) => r.request().method() === 'POST' && new URL(r.url()).pathname.endsWith('/auth/forgot-password'),
      );
      await forgotPasswordPage.el.submit.click();
      const response = await requestSent;
      // 5 — the verdict-bearing row. SRS FR-AUTH-FP-05/08: confirmation regardless of account existence,
      // no disclosure. Observed on DEV 2026-09-21: alert "User is not found" (API 404) → this stays red (Q-25).
      await expect(
        forgotPasswordPage.el.error,
        `oracle: SRS FR-AUTH-FP-05/08 — no "user not found" style disclosure (POST /auth/forgot-password answered HTTP ${response.status()})`,
      ).toBeHidden();
      await forgotPasswordPage.expectSuccess(); // 6 — `forgot-password.success` is still a placeholder id (unobserved without a registered account)
      // 7 — `<to confirm>`: SRS "Success State" copy vs CHK-AUTH-033 "Verify your email address" (Q-02). The fragment
      // both the SRS and the SPA bundle contain is asserted; the full sentence is recorded after the first observation.
      await expect(forgotPasswordPage.el.success, 'oracle: SRS §3.1.1.3 Success State copy (Q-02)').toContainText('Please check your email');
      await expect(forgotPasswordPage.el['back-to-login'], 'oracle: SRS §3.1.1.3 — Back to Login remains available').toBeVisible(); // 8
    },
  );
});
