import { test, expect } from '../../fixtures/test-fixtures';
import { login } from '../../screens/authentication/login.map';
import { forgotPassword } from '../../screens/authentication/forgot-password.map';
import { unique } from '../../utils/data';

/*
 * Login page — public TCs (Needs = none) generated by prompts/07 from
 * qa/web/01-authentication/authentication-test-cases.md on 2026-09-21.
 *
 * `*.public.spec.ts` → projects chromium-public / firefox-public: no storageState, no
 * dependency on the setup project, so this runs before any credential exists.
 * Every locator comes from screens/authentication/*.map.ts through the page-object
 * fixtures (`loginPage.el.<alias>` = the alias the TC writes). Only expect-* rows assert;
 * each verdict-bearing assertion names its oracle (SRS section or observed copy).
 * No sleeps, no skips, retries 0. Expected copy comes from the TC file; "observed
 * 2026-09-21" marks values confirmed by the headless pass of that day.
 */

/** expect-url <screen> → the route, optionally followed by /, ? or end of string. */
const atRoute = (route: string): RegExp => new RegExp(`${route}(/|\\?|$)`);

/** {{unknown.email}} — valid format, never registered (TC file → "Fixtures used"). */
const unknownEmail = (): string => `no-such-user+${unique('t')}@example.com`;

test.describe('AUTH — Login page (public)', () => {
  test(
    'TC-AUTH-001 Login page renders the title, logo, fields, controls and a disabled Log in button',
    {
      tag: [
        '@CHK-AUTH-001',
        '@CHK-AUTH-002',
        '@CHK-AUTH-003',
        '@CHK-AUTH-004',
        '@CHK-AUTH-005',
        '@CHK-AUTH-006',
        '@CHK-AUTH-007',
        '@smoke',
      ],
    },
    async ({ loginPage }) => {
      await loginPage.open(); // 1 open login
      await expect(loginPage.el.root, 'oracle: SRS §3.1.1.2 — Login page shown').toBeVisible(); // 2
      await expect(loginPage.el.title, 'oracle: SRS §3.1.1.2 title (observed 2026-09-17)').toHaveText('Log in using your credentials'); // 3
      // 4 — visibility only; "matches the design" (CHK-AUTH-002) is Blocked until Figma is readable
      await expect(loginPage.el.logo, 'oracle: SRS §3.1.1.2 logo present').toBeVisible();
      await expect(loginPage.el['email-label'], 'oracle: SRS §3.1.1.2 Email required (asterisk)').toHaveText('Email *'); // 5
      await expect(loginPage.el.email, 'oracle: SRS §3.1.1.2 Email field').toBeVisible(); // 6
      await expect(loginPage.el['password-label'], 'oracle: SRS §3.1.1.2 Password required (asterisk)').toHaveText('Password *'); // 7
      await expect(loginPage.el.password, 'oracle: SRS §3.1.1.2 Password field').toBeVisible(); // 8
      await expect(loginPage.el['password-toggle'], 'oracle: SRS §3.1.1.2 show/hide toggle').toBeVisible(); // 9
      await expect(loginPage.el['remember-me'], 'oracle: SRS FR-AUTH-LG-08 Remember me present').toBeVisible(); // 10
      await expect(loginPage.el['forgot-password'], 'oracle: SRS §3.1.1.2 Forgot password link').toBeVisible(); // 11
      await expect(loginPage.el.submit, 'oracle: SRS FR-AUTH-LG-04 — Log in disabled on an empty form').toBeDisabled(); // 12
    },
  );

  test(
    'TC-AUTH-002 Forgot password link opens the Forgot password page and Back to Login returns to Login',
    { tag: ['@CHK-AUTH-005', '@CHK-AUTH-028', '@smoke'] },
    async ({ page, loginPage, forgotPasswordPage }) => {
      await loginPage.open(); // 1
      await expect(loginPage.el.root).toBeVisible(); // 2
      await loginPage.el['forgot-password'].click(); // 3
      await expect(page, 'oracle: SRS §3.1.1.2 "Forgot Password — navigates to Forgot / Reset Password flow"').toHaveURL(atRoute(forgotPassword.route)); // 4
      await expect(forgotPasswordPage.el.root, 'oracle: SRS §3.1.1.3 — Forgot password page shown').toBeVisible(); // 5
      await forgotPasswordPage.el['back-to-login'].click(); // 6
      await expect(page, 'oracle: SRS §3.1.1.3 "Back to Login — navigates to the Login page"').toHaveURL(atRoute(login.route)); // 7
      await expect(loginPage.el.root, 'oracle: SRS §3.1.1.2 — Login page shown again').toBeVisible(); // 8
    },
  );

  test(
    'TC-AUTH-003 Invalid or empty email on Login shows the inline error "Invalid email" and keeps Log in disabled',
    { tag: ['@CHK-AUTH-003', '@CHK-AUTH-009', '@CHK-AUTH-014', '@CHK-AUTH-016', '@core'] },
    async ({ loginPage }) => {
      await loginPage.open(); // 1
      await loginPage.fillEmail('not-an-email'); // 2
      await loginPage.fillPassword('any-password-123'); // 3 — 16 characters, passes the length rule
      await expect(loginPage.el['email-error'], 'oracle: SRS FR-AUTH-LG-02 — inline error for an invalid email').toBeVisible(); // 4
      await expect(loginPage.el['email-error'], 'oracle: copy observed on DEV 2026-09-21').toHaveText('Invalid email'); // 5
      await expect(loginPage.el.submit, 'oracle: SRS FR-AUTH-LG-03/04 — submission prevented').toBeDisabled(); // 6
      await loginPage.fillEmail(''); // 7 — clear the field (the required-field copy itself is Q-10, not asserted)
      await expect(loginPage.el.submit, 'oracle: SRS FR-AUTH-LG-04 — disabled while Email is empty').toBeDisabled(); // 8
    },
  );

  test(
    'TC-AUTH-004 Valid email format and a non-empty password enable Log in',
    { tag: ['@CHK-AUTH-006', '@CHK-AUTH-008', '@CHK-AUTH-014', '@core'] },
    async ({ loginPage }) => {
      await loginPage.open(); // 1
      await loginPage.fillEmail('qa.user+auth@example.com'); // 2 — "@", "." and "+" accepted (CHK-AUTH-008)
      await expect(loginPage.el['email-error'], 'oracle: SRS FR-AUTH-LG-02 — no error for a valid format').toBeHidden(); // 3
      await expect(loginPage.el.submit, 'oracle: SRS FR-AUTH-LG-04 — disabled while Password is empty').toBeDisabled(); // 4
      await loginPage.fillPassword('any-password-123'); // 5 — 16 characters
      await expect(loginPage.el.submit, 'oracle: SRS FR-AUTH-LG-04 — enabled when email valid AND password non-empty').toBeEnabled(); // 6
    },
  );

  test(
    'TC-AUTH-005 Password show/hide toggle reveals and masks the entered password',
    { tag: ['@CHK-AUTH-004', '@extended'] },
    async ({ loginPage }) => {
      await loginPage.open(); // 1
      await loginPage.fillPassword('Visible-Pw-123'); // 2
      await expect(loginPage.el['password-toggle-masked'], 'oracle: SRS §3.1.1.2 "masked by default" (icon "eye-invisible", observed 2026-09-21)').toBeVisible(); // 3
      // secondary oracle (TC notes): the input type is the masking itself
      await expect(loginPage.el.password, 'oracle: input type=password while masked').toHaveAttribute('type', 'password');
      await loginPage.el['password-toggle'].click(); // 4
      await expect(loginPage.el['password-toggle-revealed'], 'oracle: SRS §3.1.1.2 "visibility toggle (show)" (icon "eye", observed 2026-09-21)').toBeVisible(); // 5
      await expect(loginPage.el.password, 'oracle: input type=text once revealed').toHaveAttribute('type', 'text');
      await loginPage.el['password-toggle'].click(); // 6
      await expect(loginPage.el['password-toggle-masked'], 'oracle: SRS §3.1.1.2 "visibility toggle (hide)"').toBeVisible(); // 7
      await expect(loginPage.el.password, 'oracle: input type=password when masked again').toHaveAttribute('type', 'password');
    },
  );

  test(
    'TC-AUTH-006 Unknown credentials show the banner "Incorrect email or password" and the user stays on Login',
    { tag: ['@CHK-AUTH-017', '@CHK-AUTH-018', '@core'] },
    async ({ page, loginPage }) => {
      await loginPage.open(); // 1
      await loginPage.fillEmail(unknownEmail()); // 2
      await loginPage.fillPassword('Wrong-Password-123'); // 3 — 18 characters, reaches the server
      await loginPage.submit(); // 4 — POST /auth/sign-in, rejected
      await expect(loginPage.el.error, 'oracle: SRS FR-AUTH-LG-06 — server-side error shown').toBeVisible(); // 5
      await expect(loginPage.el.error, 'oracle: SRS FR-AUTH-LG-06/07 — generic copy, no hint which credential is wrong (observed 2026-09-21)').toHaveText('Incorrect email or password'); // 6
      await expect(page, 'oracle: SRS FR-AUTH-LG-06 — no navigation on failure').toHaveURL(atRoute(login.route)); // 7
      await expect(loginPage.el.root, 'oracle: SRS §3.1.1.2 — still on Login').toBeVisible(); // 8
    },
  );

  test(
    'TC-AUTH-020 Password shorter than 12 characters on Login shows the length error and keeps Log in disabled',
    { tag: ['@CHK-AUTH-010', '@CHK-AUTH-013', '@CHK-AUTH-014', '@core'] },
    async ({ loginPage }) => {
      await loginPage.open(); // 1
      await loginPage.fillEmail('qa.user+auth@example.com'); // 2
      await loginPage.fillPassword('Short-Pw-1'); // 3 — 10 characters
      await expect(loginPage.el['password-error'], 'oracle: CHK-AUTH-010/013 + api-contract SignInDto.password minLength 12 — inline length error').toBeVisible(); // 4
      await expect(loginPage.el['password-error'], 'oracle: copy observed on DEV 2026-09-21').toContainText('Password must be at least 12 characters'); // 5 (TC: contains)
      await expect(loginPage.el.submit, 'oracle: observed 2026-09-21 — Log in disabled until the rule passes').toBeDisabled(); // 6
      await loginPage.fillPassword('Long-Enough-Pw-1'); // 7 — 16 characters
      await expect(loginPage.el['password-error'], 'oracle: error cleared once the rule passes').toBeHidden(); // 8
      await expect(loginPage.el.submit, 'oracle: SRS FR-AUTH-LG-04 — enabled with a valid email and a passing password').toBeEnabled(); // 9
    },
  );
});
