import fs from 'node:fs';
import path from 'node:path';
import type { ElementSpec } from '../../screens/resolve';
import type { Harvest, HarvestedElement, PageRecord, ReconRun, SubStateRecord } from './types';

const RESOLVE_TS = path.resolve(__dirname, '..', '..', 'screens', 'resolve.ts');

// --- small helpers -------------------------------------------------------------

/** Single-quoted TS string literal. */
function q(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, '\\n')}'`;
}

function key(alias: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(alias) ? alias : q(alias);
}

function cell(s: string | null | undefined): string {
  return (s ?? '').replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').trim();
}

function code(s: string | null | undefined): string {
  const v = (s ?? '').replace(/\r?\n/g, ' ').replace(/`/g, "'").replace(/\|/g, '\\|').trim();
  return v ? `\`${v}\`` : '';
}

function fmtDuration(ms: number): string {
  const s = Math.round(ms / 1000);
  return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m ${s % 60}s`;
}

function strOrRegex(v: string | RegExp): string {
  return v instanceof RegExp ? `/${v.source}/${v.flags}` : q(v);
}

export function specToTs(spec: ElementSpec): string {
  if ('testId' in spec) return `{ testId: ${q(spec.testId)} }`;
  if ('role' in spec) {
    const name = spec.name !== undefined ? `, name: ${strOrRegex(spec.name)}` : '';
    const exact = spec.exact === undefined ? '' : `, exact: ${spec.exact}`;
    return `{ role: ${q(spec.role)}${name}${exact} }`;
  }
  if ('label' in spec) return `{ label: ${strOrRegex(spec.label)}${spec.exact === undefined ? '' : `, exact: ${spec.exact}`} }`;
  return `{ text: ${strOrRegex(spec.text)}${spec.exact === undefined ? '' : `, exact: ${spec.exact}`} }`;
}

function describeElement(el: HarvestedElement): string {
  const what = el.role ? el.role : el.kind;
  const label = el.name || el.text || el.placeholder || '';
  return label ? `${what} "${label.slice(0, 60)}"` : `${what} (unnamed)`;
}

function importPath(fromFile: string): string {
  let rel = path.relative(path.dirname(fromFile), RESOLVE_TS).split(path.sep).join('/').replace(/\.ts$/, '');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel;
}

// --- draft maps ------------------------------------------------------------

function emitElements(h: Harvest): string[] {
  const lines: string[] = [];
  for (const el of h.elements) {
    if (el.spec) {
      const parts = [`via: ${el.via}`, el.unique ? 'unique' : 'NOT unique'];
      if (el.gap) parts.push(`${el.gap.severity}: ${el.gap.reason}`);
      if (el.state) parts.push(`state: ${el.state}`);
      if (el.disabled) parts.push('disabled at harvest time');
      parts.push(...el.notes);
      lines.push(`    ${key(el.alias)}: ${specToTs(el.spec)}, // ${parts.join(' | ')}`);
    } else {
      const why = el.gap ? el.gap.reason : 'no unique locator';
      const suggest = el.gap ? el.gap.suggestedTestId : `<screen>-${el.alias}`;
      lines.push(`    // GAP ${el.alias}: ${describeElement(el)} — ${why} → ask for data-testid="${suggest}" (${el.hint})`);
    }
  }
  for (const t of h.tables) {
    const name = t.name ? ` "${t.name}"` : '';
    lines.push(`    // table ${t.index + 1}${name} (${t.hint}): columns [${t.headers.join(', ')}] — ${t.rowCount} rows${t.empty ? ' (empty)' : ''} — row template: ${t.rowTemplate}`);
  }
  for (const f of h.forms) {
    const fields = f.fields.map((x) => `${x.label ?? x.name ?? x.tag} (${x.type}${x.required ? ', required' : ''})`).join(', ');
    lines.push(`    // form ${f.index + 1} (${f.hint}): fields [${fields}]${f.submitText ? ` — submit "${f.submitText}"` : ''}`);
  }
  if (h.truncated) lines.push('    // NOTE: element list truncated at 250 — narrow the page or split the screen');
  return lines;
}

function emitScreen(constName: string, id: string, route: string, h: Harvest, doc: string[]): string {
  const out: string[] = [];
  out.push('/**');
  for (const d of doc) out.push(` * ${d}`);
  out.push(' */');
  out.push(`export const ${constName} = {`);
  out.push(`  id: ${q(id)},`);
  out.push(`  route: ${q(route)},`);
  out.push('  elements: {');
  out.push(...emitElements(h));
  out.push('  },');
  out.push('} as const satisfies ScreenMap;');
  return out.join('\n');
}

export function renderDraftMap(rec: PageRecord, run: ReconRun, filePath: string): string | null {
  const h = rec.harvest;
  if (!h) return null;
  const header = [
    `// DRAFT screen map — generated by recon.ts on ${run.meta.startedAt} from ${rec.finalUrl}`,
    `// module: ${run.meta.module} | route pattern: ${rec.pattern} | title: ${h.title}${h.h1 ? ` | h1: ${h.h1}` : ''}`,
    '//',
    '// Curate before use (automation/web/playwright/scripts/README.md → "Curation workflow"):',
    '//   1. rename aliases by PURPOSE (login.submit, never login.button-2); keep them stable across platforms;',
    '//   2. drop decorative/duplicate entries; resolve every "GAP" line via the testability contract (gaps.md);',
    "//   3. move the const to automation/web/playwright/screens/<module>/<screen>.map.ts and fix the import to '../resolve';",
    '//   4. replace weak locators (text / placeholder-derived names) with data-testid once devs ship them.',
    `import type { ScreenMap } from ${q(importPath(filePath))};`,
    '',
  ];
  const blocks: string[] = [];
  blocks.push(
    emitScreen(rec.constName, rec.slug, rec.route, h, [
      `${rec.slug} — ${h.title || rec.route}${rec.navPath.length ? ` (reached via: ${rec.navPath.join(' › ')})` : ' (start page)'}`,
      `${h.elements.length} elements, ${h.forms.length} forms, ${h.tables.length} tables${h.hasRootTestId ? '' : ' — no <screen>-root test id found (contract §2.3)'}`,
    ]),
  );
  for (const s of rec.subStates) {
    blocks.push(
      emitScreen(s.constName, s.mapId, rec.route, s.harvest, [
        `Sub-state ${s.id} (${s.kind}) — opened by \`${rec.slug}.${s.opener.alias}\` (${s.opener.kind} "${s.opener.name}"), closed by ${s.closedBy}.`,
        `Locators were verified page-wide while the ${s.kind} was open — resolve them only in that state.`,
      ]),
    );
  }
  return `${header.join('\n')}${blocks.join('\n\n')}\n`;
}

// --- inventory.md ------------------------------------------------------------------

export function renderInventory(run: ReconRun): string {
  const m = run.meta;
  const out: string[] = [];
  out.push(`# Recon inventory — ${m.module} — ${m.baseUrl}`);
  out.push('');
  out.push(`Generated by \`automation/web/playwright/scripts/recon.ts\` on ${m.startedAt}. Raw material for screen maps and checklists — curate, never commit as-is.`);
  out.push('');
  out.push('## Run');
  out.push('');
  out.push('| Setting | Value |');
  out.push('|---|---|');
  out.push(`| Base URL | ${m.baseUrl} |`);
  out.push(`| Start | ${m.startUrl} |`);
  out.push(`| Storage state (auth) | ${m.storageState ? `yes (${m.storageStateFile})` : 'no'} |`);
  out.push(`| Limits | ${m.maxPages} pages, ${m.maxMinutes} min |`);
  out.push(`| Filters | allow: ${m.allow ? code(m.allow) : '—'}, deny: ${m.deny ? code(m.deny) : '—'} (+ built-in logout/sign-out deny) |`);
  out.push(`| Explore states | ${m.exploreStates ? 'on' : 'off'} |`);
  out.push(`| Probe validation | ${m.probeValidation ? 'on' : 'off'} |`);
  out.push(`| Hash-routed | ${m.hashRouted ? 'yes' : 'no'} |`);
  out.push(`| Duration | ${fmtDuration(m.durationMs)} |`);
  out.push(`| Pages harvested | ${run.pages.length} (sub-states: ${run.pages.reduce((n, p) => n + p.subStates.length, 0)}) |`);
  out.push(`| Routes not visited | ${run.notVisited.length} |`);
  out.push(`| Output | ${m.outDir} |`);
  out.push('');
  if (run.authRequired) {
    const detail = run.notes.find((n) => n.startsWith('Auth required for the rest: '))?.slice('Auth required for the rest: '.length);
    out.push(`> **Auth required for the rest.** ${detail ?? 'The crawl ran without --storage-state.'}`);
    out.push('');
  }
  for (const n of run.notes.filter((n) => !n.startsWith('Auth required'))) {
    out.push(`> ${n}`);
    out.push('');
  }

  out.push('## Pages');
  out.push('');
  out.push('| # | Route pattern | Title | h1 | Nav path | Interactive | Forms | Tables | Dialogs | Gaps | Console errors | Module | Notes |');
  out.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  for (const p of run.pages) {
    const notes = [...p.notes, ...p.errors.map((e) => `ERROR: ${e}`)];
    if (p.harvest === null) notes.unshift('not harvested');
    out.push(
      `| ${p.index + 1} | ${code(p.pattern)} | ${cell(p.title)} | ${cell(p.h1)} | ${p.navPath.length ? cell(p.navPath.join(' › ')) : '(start)'} | ${p.counts.interactive} | ${p.counts.forms} | ${p.counts.tables} | ${p.counts.dialogs} | ${p.counts.gaps} | ${p.counts.consoleErrors} | ${cell(p.module)} | ${cell(notes.join('; '))} |`,
    );
  }
  out.push('');

  const subs = run.pages.flatMap((p) => p.subStates.map((s) => ({ p, s })));
  if (subs.length) {
    out.push('## Sub-states (dialogs, menus, drawers, tab panels)');
    out.push('');
    out.push('| Page | State | Opener | Kind | Interactive | Gaps | Closed by |');
    out.push('|---|---|---|---|---|---|---|');
    for (const { p, s } of subs) {
      const interactive = s.harvest.elements.filter((e) => ['button', 'link', 'textbox', 'checkbox', 'radio', 'switch', 'tab', 'menuitem', 'combobox', 'listbox', 'option', 'editable'].includes(e.kind)).length;
      out.push(`| ${code(p.pattern)} | ${code(s.id)} | ${cell(`${s.opener.kind} "${s.opener.name}"`)} | ${s.kind} | ${interactive} | ${s.gaps} | ${s.closedBy} |`);
    }
    out.push('');
  }

  const instances = Object.entries(run.instances).filter(([, urls]) => urls.length > 0);
  if (instances.length) {
    out.push('## Route instances (one visited per pattern)');
    out.push('');
    out.push('| Pattern | Other instances seen |');
    out.push('|---|---|');
    for (const [pattern, urls] of instances) out.push(`| ${code(pattern)} | ${urls.length} — ${cell(urls.slice(0, 3).join(', '))}${urls.length > 3 ? ', …' : ''} |`);
    out.push('');
  }

  out.push('## Routes not visited (limit reached / denied / redirected)');
  out.push('');
  if (run.notVisited.length === 0) out.push('None — every discovered same-origin route was visited.');
  else {
    out.push('| Route pattern | Reason | Found on |');
    out.push('|---|---|---|');
    for (const nv of run.notVisited) out.push(`| ${code(nv.pattern)} | ${cell(nv.reason)} | ${nv.foundOn ? code(nv.foundOn) : '(start)'} |`);
  }
  out.push('');

  const probes = run.pages.filter((p) => p.validationProbe);
  if (probes.length) {
    out.push('## Validation probes (empty submit)');
    out.push('');
    out.push('| Page | Button | Messages | URL after |');
    out.push('|---|---|---|---|');
    for (const p of probes) {
      const v = p.validationProbe;
      if (!v) continue;
      const msgs = v.messages.map((x) => (x.field ? `${x.field}: ${x.message}` : x.message)).join('; ') || '(none captured)';
      out.push(`| ${code(p.pattern)} | ${cell(v.button)} | ${cell(msgs)} | ${cell(v.urlAfter)}${v.note ? ` — ${cell(v.note)}` : ''} |`);
    }
    out.push('');
  }

  const errored = run.pages.filter((p) => p.errors.length || p.consoleErrors.length);
  if (errored.length) {
    out.push('## Errors');
    out.push('');
    for (const p of errored) {
      out.push(`- ${code(p.pattern)}`);
      for (const e of p.errors) out.push(`  - tool: ${cell(e)}`);
      for (const c of p.consoleErrors) out.push(`  - console: ${cell(c)}`);
    }
    out.push('');
  }
  return `${out.join('\n')}\n`;
}

// --- gaps.md -------------------------------------------------------------------

interface GapRow {
  screen: string;
  el: HarvestedElement;
  state: string | null;
}

function collectGaps(rec: PageRecord): GapRow[] {
  const rows: GapRow[] = [];
  if (rec.harvest) for (const el of rec.harvest.elements) if (el.gap) rows.push({ screen: rec.slug, el, state: el.state ?? null });
  for (const s of rec.subStates) for (const el of s.harvest.elements) if (el.gap) rows.push({ screen: s.mapId, el, state: s.id });
  return rows;
}

function gapTable(rows: GapRow[]): string[] {
  const out: string[] = [];
  out.push('| Element | Where (hint) | Why | Add |');
  out.push('|---|---|---|---|');
  for (const r of rows) {
    const g = r.el.gap;
    if (!g) continue;
    const where = r.state ? `${r.state}: ${r.el.hint}` : r.el.hint;
    out.push(`| ${cell(describeElement(r.el))} | ${code(where)} | ${cell(g.reason)} | ${code(`data-testid="${g.suggestedTestId}"`)} |`);
  }
  return out;
}

export function renderGaps(run: ReconRun): string {
  const m = run.meta;
  const out: string[] = [];
  const all = run.pages.flatMap(collectGaps);
  const blocking = all.filter((r) => r.el.gap?.severity === 'blocking');
  const weak = all.filter((r) => r.el.gap?.severity === 'weak');
  out.push(`# Testability gaps — ${m.module} — ${m.baseUrl}`);
  out.push('');
  out.push(`Generated by \`recon.ts\` on ${m.startedAt}. Handover to the dev team per \`docs/requirements/shared/testability-contract.md\` (§1 web: \`data-testid="<screen>-<element>"\`). A screen without ids is not ready for QA: the affected checks stay **Blocked**, never Passed.`);
  out.push('');
  out.push(`**${blocking.length} blocking** (no unique stable locator) and **${weak.length} weak** (works today, copy-fragile) across ${run.pages.length} pages. Suggested ids use the auto-generated alias — rename together with the alias during curation.`);
  out.push('');
  for (const rec of run.pages) {
    const rows = collectGaps(rec);
    const missing: string[] = [];
    if (rec.harvest && !rec.harvest.hasRootTestId) missing.push(`no \`${rec.slug}-root\` on the screen container (§2.3)`);
    for (const s of rec.subStates) if (s.kind !== 'tabpanel' && !s.harvest.hasRootTestId) missing.push(`no \`${s.mapId}-root\` on the ${s.kind} opened by \`${s.opener.alias}\` (§2.8)`);
    if (rows.length === 0 && missing.length === 0) continue;
    out.push(`## ${rec.slug} (${code(rec.route)})`);
    out.push('');
    const b = rows.filter((r) => r.el.gap?.severity === 'blocking');
    const w = rows.filter((r) => r.el.gap?.severity === 'weak');
    if (b.length) {
      out.push('### Blocking — no unique stable locator');
      out.push('');
      out.push(...gapTable(b));
      out.push('');
    }
    if (w.length) {
      out.push('### Weak — resolves today, but by copy (text / placeholder) or without an id where the contract requires one');
      out.push('');
      out.push(...gapTable(w));
      out.push('');
    }
    if (missing.length) {
      out.push('### Missing per contract');
      out.push('');
      for (const x of missing) out.push(`- ${x}`);
      out.push('');
    }
  }
  out.push('## Alias → id handshake (paste into the ticket, contract §3)');
  out.push('');
  out.push('| Alias (TC) | Web `data-testid` | Android `resource-id` / testTag | iOS `accessibilityIdentifier` | Flutter `Semantics(identifier:)` |');
  out.push('|---|---|---|---|---|');
  const handshake = new Set<string>();
  for (const rec of run.pages) {
    if (!rec.harvest) continue;
    handshake.add(`| ${code(`${rec.slug}.root`)} | ${code(`${rec.slug}-root`)} | | | |`);
    for (const s of rec.subStates) if (s.kind !== 'tabpanel') handshake.add(`| ${code(`${s.mapId}.root`)} | ${code(`${s.mapId}-root`)} | | | |`);
    for (const r of collectGaps(rec)) {
      const g = r.el.gap;
      if (!g) continue;
      handshake.add(`| ${code(`${r.screen}.${r.el.alias}`)} | ${code(g.suggestedTestId)} | | | |`);
    }
  }
  out.push(...handshake);
  out.push('');
  return `${out.join('\n')}\n`;
}

// --- writer --------------------------------------------------------------------

export interface WrittenOutputs {
  inventory: string;
  gaps: string;
  summary: string;
  drafts: string[];
}

export function writeOutputs(run: ReconRun, outDir: string): WrittenOutputs {
  const screensDir = path.join(outDir, 'screens');
  fs.mkdirSync(screensDir, { recursive: true });
  const drafts: string[] = [];
  for (const rec of run.pages) {
    const file = path.join(screensDir, `${rec.slug}.map.draft.ts`);
    const src = renderDraftMap(rec, run, file);
    if (src === null) continue;
    fs.writeFileSync(file, src);
    drafts.push(file);
  }
  const inventory = path.join(outDir, 'inventory.md');
  fs.writeFileSync(inventory, renderInventory(run));
  const gaps = path.join(outDir, 'gaps.md');
  fs.writeFileSync(gaps, renderGaps(run));
  const summary = path.join(outDir, 'summary.json');
  fs.writeFileSync(summary, `${JSON.stringify(run, null, 2)}\n`);
  return { inventory, gaps, summary, drafts };
}

/** Sub-state helper for callers that need the list flattened. */
export function allSubStates(run: ReconRun): SubStateRecord[] {
  return run.pages.flatMap((p) => p.subStates);
}
